<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>edu.icet</groupId>
        <artifactId>clothify-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>clothify-api</artifactId>
    <name>Clothify API</name>

    <dependencies>
        <dependency>
            <groupId>edu.icet</groupId>
            <artifactId>clothify-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.5.6</version>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
            <resource>
                <directory>../clothify-core/src/main/resources</directory>
                <includes>
                    <include>db.properties</include>
                </includes>
            </resource>
            <resource>
                <directory>../clothify-desktop/src/main/resources/images</directory>
                <targetPath>images</targetPath>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
            </plugin>
        </plugins>
    </build>
</project>
