db.url=jdbc:mysql://localhost:3306/clothify_store_db
db.user=root
db.password=1234
app.tax.rate=0.0
app.low.stock.threshold=5
app.store.name=Clothify Store
app.session.timeout.minutes=30
app.backup.dir=backups
app.backup.interval.hours=0
app.mysql.dump.path=mysqldump
app.mysql.path=mysql
